### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by jeffallen** [dedis/student_21_pop#1]
Choose a license, get Prof Ford's approval, and commit it to the repo.

**Comment by bford** [comment]
Thanks for raising this issue - as good a starting issue as any. 👍 

I'm generally inclined "by default" to use the GNU GPL for front-end user-facing code, and the GNU Affero GPL for back-end server type code, and then consider "looser" open-source licenses later as demand requires (for example, a potential major partner expresses interest in using and helping with some code but only under a looser license).  We can always loosen the license later, but we can't really tighten it.

But any questions/concerns/discussion about this is welcome.  In any case, not critically important until there's a non-trivial amount of code covered by the license. :)

**Comment by ineiti** [comment]
@tharvik raised the issue that for the (A|L)GPL for go-code is nearly impossible, as everything is linked statically and thus all libraries would need to be licensed under the (A|L)GPL. So you'd have to either chose another license like MPL, or write an exception in the license file that states that this code is allowed to be statically linked to other code.

**Comment by pierluca** [comment]
I've added GNU AGPL License as it is the most "restrictively-free" license.
We do have committers' agreements and we can change the license at a later date based on @ineiti 's or others' remarks.
I'll close the issue for the time being.
