### ISSUE TITLE
Fe2: Camera source not found 

### ISSUE THREAD

**Issue by celinecamacho** [dedis/student_21_pop#262]
**Issue**
On the connect tab the camera should appear after accepting the permissions, instead a black box appears. The problem comes from the camera source that is not found.

**Comment by pierluca** [comment]
has this problem been addressed with the Java team ?
if not, is there any lead on how to solve this ?

**Comment by celinecamacho** [comment]
This seemed to be an issue with my android emulator I used and not the project
