### ISSUE TITLE
Protocol: Channel id encoding

### ISSUE THREAD

**Issue by flmichel** [dedis/student_21_pop#281]
The channel id for a lao is stored as follow: `“channel”: “/root/<lao_id>”`. With `<lao_id>` encoded in base64 (At least the go backend is expecting this encoding). And the channel id for an election would be `“channel”: “/root/<lao_id>/<election_id>”` with `<lao_id>`and `<election_id>`in base64. We might have `/` in the in the base64 encoding which might be a bit confusing for the election channel id. Should we used [base64url](https://tools.ietf.org/html/rfc4648#section-5) instead?

**Comment by pierluca** [comment]
That seems like a potentially interesting option. You might want to consider evaluating its support for it across the different stacks :)

**Comment by pierluca** [comment]
We need to come to a decision on this, @dedis/student_21-1_pop !

Can at least one person from each tech stack take responsibility for this, and agree to using base64url or suggest an alternative ? 

Thanks !

**Comment by lhmerino** [comment]
+1 for base64url

**Comment by Adalsteinnjons** [comment]
I can take care of this for the Typescript frontend. 
Should we also use base64url for all the other IDs, such as the Ids of the events (Meetings, Roll-Calls, Elections,...) or just change the channel ID? 
On the web front-end only the channel ID causes problems, so it might be ok to keep the others as is.

**Comment by Walfar** [comment]
In Java, every IDs are encoded using the same hashing method. If I change the encoding of this hash from a base64 encoding to a base64url, it will change the IDs for all events aswell. So I think it's best if we use base64url everywhere, even if it only causes problem for the channel ID.

**Comment by Adalsteinnjons** [comment]
> In Java, every IDs are encoded using the same hashing method. If I change the encoding of this hash from a base64 encoding to a base64url, it will change the IDs for all events aswell. So I think it's best if we use base64url everywhere, even if it only causes problem for the channel ID.

You're right. The same applies to the TS front-end. 
Best to use the same encoding everywhere.

**Comment by Adalsteinnjons** [comment]
@gnarula It is in the same place in the front-end. 
Everything is encoded in this file
https://github.com/dedis/student_21_pop/blob/f2d0721aa17155ad20cc21975430555ce9899242/fe1-web/model/objects/Base64.ts#L1-L22

**Comment by pierluca** [comment]
As this was agreed upon and all stacks have implemented this, I'm closing down this issue.
