### ISSUE TITLE
Be1: meeting/create response does not respect the JSON-RPC protocol

### ISSUE THREAD

**Issue by pierluca** [dedis/student_21_pop#284]
submitting this JSON-RPC request

```
{
   "id":3,
   "method":"publish",
   "params":{
      "channel":"/root/InXJxwoGiUC1wWjmq0MYXFFg0SvErmH0aNtoCu88OF0=",
      "message":{
         "data":"eyJvYmplY3QiOiJtZWV0aW5nIiwiYWN0aW9uIjoiY3JlYXRlIi…1VDRlWGM3VVVhSHJNaDVaMm1sZWJSYmJ6ZlI0Uk9ZTnc9In0=",
         "message_id":"XVr8I/iusOEJ424frFFmJddSB43kAp6fr1zo1XFMcKo=",
         "sender":"S7+QrjH8suZZXAFhAwhiXnpgX6DD+DhNuLjnkNDYolc=",
         "signature":"nCApA1hQaya1WWCeIxLru+XiprMUvual580DUk4AyWVXz4/arAQj8xy8oNcEzjRinN5Hd+e1ByM4BWYgQ+NqDA==",
         "witness_signatures":[]
      }
   }
}
```

I got this in response:

```
{
   "jsonrpc":"2.0",
   "Subscribe":null,
   "Unsubscribe":null,
   "Publish":null,
   "Catchup":null,
   "Broadcast":{
      "method":"broadcast",
      "params":{
         "channel":"/root/InXJxwoGiUC1wWjmq0MYXFFg0SvErmH0aNtoCu88OF0=",
         "message":{
            "message_id":"XVr8I/iusOEJ424frFFmJddSB43kAp6fr1zo1XFMcKo=",
            "data":"eyJvYmplY3QiOiJtZWV0aW5nIiwiYWN0aW9uIjoiY3JlYXRlIiwibmFtZSI6IkFBYWFhYSIsImNyZWF0aW9uIjoxNjE2Nzk2MTMyLCJzdGFydCI6MTYxNzMxMDkyNiwiZW5kIjoxNjE3MzEwOTI2LCJpZCI6IkxIVFBjc0dKUEh1VDRlWGM3VVVhSHJNaDVaMm1sZWJSYmJ6ZlI0Uk9ZTnc9In0=",
            "sender":"S7+QrjH8suZZXAFhAwhiXnpgX6DD+DhNuLjnkNDYolc=",
            "signature":"nCApA1hQaya1WWCeIxLru+XiprMUvual580DUk4AyWVXz4/arAQj8xy8oNcEzjRinN5Hd+e1ByM4BWYgQ+NqDA==",
            "witness_signatures":[
               
            ]
         }
      }
   }
}
```

This clearly doesn't respect the JSON-RPC protocol.

**Comment by pierluca** [comment]
Never mind, it was a mistake on my part, running an outdated version of the Go backend.

**Comment by pierluca** [comment]
Actually, I have been able to reproduce this issue on commit b9d1d228 , which is based on master (as of 2021-03-26).
As such, it seems to be still a problem.

**Comment by flmichel** [comment]
I haven't been able to reproduce this bug neither on commit `[b9d1d22]`(https://github.com/dedis/student_21_pop/commit/b9d1d228a9732bd0b8baf275de28fce824595859) or on the master. I believe meeting messages are not handled anymore on the go bakcend ([processMeetingObject](https://github.com/dedis/student_21_pop/blob/2d587c80d0e76e34764310c9336ab0a78b62d262/be1-go/hub/organizer.go#L421)).

**Comment by pierluca** [comment]
The meeting messages are not handled, but they are still broadcast.

I believe the issue is with the broadcasting itself and the JSON marshalling of the query, so the issue is much bigger than I had originally identified. @gnarula isn't the following buggy? I don't see how it could respect the JSON-RPC protocol.
https://github.com/dedis/student_21_pop/blob/master/be1-go/message/query.go#L177
