### ISSUE TITLE
Fe2: Expanding arrow for future events not working

### ISSUE THREAD

**Issue by Kar1213** [dedis/student_21_pop#290]
In the LAO detail the arrows for past and present events work but not the one for future. As a result, the "Future" group cannot be expanded.

The concerned files are EventExpandableListViewAdapter.java and layout_event_category.xml

**Comment by gnarula** [comment]
The solution is to set the focusable property false in code. Please refer to https://stackoverflow.com/a/11857492 for more information.

**Comment by pierluca** [comment]
I believe #291 resolved this issue. I'm closing it.
