### ISSUE TITLE
be1-go server sends incorrect broadcast after an updateLao message

### ISSUE THREAD

**Issue by Kar1213** [dedis/student_21_pop#311]
According to the protocol specification, when the front-end sends an updateLao message the server should send a stateLao broadcast message. Instead the front-end currently receives an updateLao broadcast. Is this indeed an implementation issue?

**Comment by pierluca** [comment]
This is incorrect.

The server only broadcasts what the clients send.

It is the client's responsibility to collect signatures and send the stateLao message once the signatures have been collected.

See #255 to see the full flow.

If you've read this in the documentation, the documentation probably needs updating.

**Comment by Kar1213** [comment]
Ok it was indeed a misunderstanding from my side, thank you.
