### ISSUE TITLE
Message id generation doesn't adhere to specs

### ISSUE THREAD

**Issue by gnarula** [dedis/student_21_pop#338]
Fe2's message id generation doesn't adhere to the spec:

https://github.com/dedis/student_21_pop/blob/23725078764cc4af2f6e2031748d91ee2cb8739f/fe2-android/app/src/main/java/com/github/dedis/student20_pop/model/network/method/message/MessageGeneral.java#L91

The hash should be calculated using `Hash.hash(Base64(data), Base64(signature))`

**Comment by Walfar** [comment]
Should be fixed in my PR for base64url encoding

**Comment by GabrielFleischer** [comment]
This has now been fixed
