### ISSUE TITLE
Attendees can't see LAO's QR code during rollcall

### ISSUE THREAD

**Issue by Kar1213** [dedis/student_21_pop#339]
As we discussed at the PoP party and in the last meeting, attendees are not able to see the QR code of the LAO once a rollcall has started. This is due to the fact that the QR code is only displayed in the organizer UI.
A solution is to also display the QR code in the attendees' UI under the LAO's properties.

**Comment by pierluca** [comment]
Should this issue be closed @Kar1213  ?
