### ISSUE TITLE
[BUG] The android key-set fails on real device

### ISSUE THREAD

**Issue by GabrielFleischer** [dedis/student_21_pop#551]
### Description (Actual behavior)
The android key-set manager cannot be built on real devices.

### Expected behavior
The expected behavior is that the app is able to create the manager and continue its start process.

### How to reproduce
Start the app.

### Version & Environment
This bug was reproduced on:
- Commit: 9433e1731f0ebde5c934beb3e0b303db89a0db27

##### Front-ends:
- [ ] Fe1-Web (please include browser's names & version)
- [x] Fe2-Android (please specify if phone or emulation, and Android version)
- [ ] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [x] Not applicable

##### Environment (as applicable):
 - Device: Asus Zenfone (Mine)
 - OS: Android 9

### Workaround
Using an emulator or some other device (to be tested)

### Impact
The app cannot be opened

### Possible root cause
This is probably related to https://github.com/google/tink/issues/413 and https://github.com/google/tink/issues/504

E/

> AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.github.dedis.popstellar, PID: 30501
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.dedis.popstellar/com.github.dedis.popstellar.ui.home.HomeActivity}: java.lang.RuntimeException: Could not provide AndroidKeysetManager
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2919)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:198)
>         at android.app.ActivityThread.main(ActivityThread.java:6732)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
>      Caused by: java.lang.RuntimeException: Could not provide AndroidKeysetManager
>         at com.github.dedis.popstellar.ViewModelFactory.<init>(ViewModelFactory.java:55)
>         at com.github.dedis.popstellar.ViewModelFactory.getInstance(ViewModelFactory.java:35)
>         at com.github.dedis.popstellar.ui.home.HomeActivity.obtainViewModel(HomeActivity.java:173)
>         at com.github.dedis.popstellar.ui.home.HomeActivity.onCreate(HomeActivity.java:41)
>         at android.app.Activity.performCreate(Activity.java:7173)
>         at android.app.Activity.performCreate(Activity.java:7164)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054) 
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:198) 
>         at android.app.ActivityThread.main(ActivityThread.java:6732) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
>      Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
>         at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
>         at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
>         at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
>         at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
>         at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
>         at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
>         at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
>         at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
>         at com.github.dedis.popstellar.Injection.provideAndroidKeysetManager(Injection.java:91)
>         at com.github.dedis.popstellar.ViewModelFactory.<init>(ViewModelFactory.java:53)
>         at com.github.dedis.popstellar.ViewModelFactory.getInstance(ViewModelFactory.java:35) 
>         at com.github.dedis.popstellar.ui.home.HomeActivity.obtainViewModel(HomeActivity.java:173) 
>         at com.github.dedis.popstellar.ui.home.HomeActivity.onCreate(HomeActivity.java:41) 
>         at android.app.Activity.performCreate(Activity.java:7173) 
>         at android.app.Activity.performCreate(Activity.java:7164) 
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899) 
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3054) 
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:198) 
>         at android.app.ActivityThread.main(ActivityThread.java:6732) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by arnauds5** [comment]
### Workaround
Clear all data for the app in the android settings (it will change the private/public key).

### Possible root cause
When the app is reinstalled, the keystore is maybe cleared but not the SharedPreferences.
Perhaps the app try to load the previous key with an invalid master key or something like that.

**Comment by karandatwani92** [comment]
> ### Workaround
> Clear all data for the app in the android settings (it will change the private/public key).
> 
> ### Possible root cause
> When the app is reinstalled, the keystore is maybe cleared but not the SharedPreferences. Perhaps the app try to load the previous key with an invalid master key or something like that.

Exactly this is happening

**Comment by GabrielFleischer** [comment]
This should have been fixed.

I will try to do a recover procedure when the Keyset fails to load.

Do you have any logs ?
