### ISSUE TITLE
[BUG] Json Schemas not loaded entierly from local storage

### ISSUE THREAD

**Issue by arnauds5** [dedis/student_21_pop#630]
### Description (Actual behavior)
When loading Json schemas, it seems that only the root is loaded from local storage, then it tried to load others from github URL (that don't exist yet).

### Expected behavior
Using only the schemas from local files.

### Version & Environment
This bug was reproduced on:
- Commit: 3b15e7617cfe22e84213afbac1afa393cb056849

##### Front-ends:
- [x] Fe2-Android

### Impact
We can't use schemas that are not yet merged to master.

### Possible root cause
The $id of all json schemas are based on the github url and $ref are relative path.
Maybe the lib was not used correctly to only use local resource or maybe the json schemas are not correctly refering others as relative path in local resources ?

**Comment by arnauds5** [comment]
The schemas referenced by $ref can't be use as a relative path because it will use the $id as the base URL,
https://json-schema.org/understanding-json-schema/structuring.html#structuring

**Comment by arnauds5** [comment]
I can see multiple solutions to the problem:
- Remove $id in all the json schemas, but we loose this unique identifier.
- Use an URL mapping with current lib, but it require a line of code for each file and need to be maintained.
- Use another lib that allow custom URI factory (for replacing https://github..../ to resource:/...).

**Comment by pierluca** [comment]
> Use an URL mapping with current lib, but it require a line of code for each file and need to be maintained.

This is how the typescript front-end handles it, because there was no other choice (there) to fix this issue :-/
