### ISSUE TITLE
Inconsistency across ActionTypes in the messageData of the protocol

### ISSUE THREAD

**Issue by tuomas-p** [dedis/student_21_pop#645]
### Description (Actual behavior)
There are ActionTypes written in camelCase (addBroadcast in dataAddChirpBroadcast, deleteBroadcast in dataDeleteChirpBroadcast), some in kebab-case (elect-accept in dataElectAccept) and snake_case (in the messageData from previous semesters).

##### Front-ends:
- [ ] Fe1-Web (please include browser's names & version)
- [ ] Fe2-Android (please specify if phone or emulation, and Android version)
- [ x] Not applicable

##### Back-ends:
- [ ] Be1-Go
- [ ] Be2-Scala
- [ x] Not applicable

### Workaround
For now, as the front-ends and back-ends respect the protocol, there are no issues, but for the code to function after the changes have been made, all front- and back-ends should also change their code.

### Impact
Inconsistency in the protocol.

**Comment by rjaccard** [comment]
https://github.com/dedis/student_21_pop/pull/646 solved

**Comment by rjaccard** [comment]
merged
